import type { EntradaFenologica } from './types';

// Hemisferio sur: enero = verano, julio = invierno/reposo
// Kc: FAO-56 tabla 12. Umbrales: estimación INIA adaptada a condiciones secano costero Chile.

export const CATALOGO_FENOLOGIA: EntradaFenologica[] = [
  // ─── PALTO HASS ───────────────────────────────────────────────────────────
  { cultivo: 'palto_hass', mes: 1,  fase: 'desarrollo_fruto', kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Pleno verano. Demanda hídrica máxima. Fruto en engrose activo.' },
  { cultivo: 'palto_hass', mes: 2,  fase: 'desarrollo_fruto', kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Continúa engrose. Temperatura alta, ET elevada.' },
  { cultivo: 'palto_hass', mes: 3,  fase: 'maduracion',       kcReferencia: 0.95, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Inicio maduración. Kc baja levemente hacia otoño.' },
  { cultivo: 'palto_hass', mes: 4,  fase: 'cosecha',          kcReferencia: 0.85, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Cosecha principal variedades tempranas Hass.' },
  { cultivo: 'palto_hass', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.75, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Post-cosecha. Recuperación foliar. Menor demanda.' },
  { cultivo: 'palto_hass', mes: 6,  fase: 'reposo',           kcReferencia: 0.60, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas', notas: 'Invierno. Crecimiento mínimo. Lluvias reducen necesidad de riego.' },
  { cultivo: 'palto_hass', mes: 7,  fase: 'reposo',           kcReferencia: 0.55, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Mes más frío. Kc mínimo anual. Riego de mantención solamente.' },
  { cultivo: 'palto_hass', mes: 8,  fase: 'reposo',           kcReferencia: 0.60, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas', notas: 'Fin invierno. Inicio diferenciación floral en yemas.' },
  { cultivo: 'palto_hass', mes: 9,  fase: 'brotacion',        kcReferencia: 0.70, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Primavera temprana. Brotación. Kc en ascenso.' },
  { cultivo: 'palto_hass', mes: 10, fase: 'floracion',        kcReferencia: 0.80, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración. Sensibilidad hídrica alta. Déficit afecta cuaje.' },
  { cultivo: 'palto_hass', mes: 11, fase: 'cuaje',            kcReferencia: 0.90, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y caída fisiológica. Mantener humedad uniforme.' },
  { cultivo: 'palto_hass', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 0.95, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Inicio engrose rápido. Verano comenzando.' },

  // ─── CÍTRICOS ─────────────────────────────────────────────────────────────
  { cultivo: 'citricos', mes: 1,  fase: 'desarrollo_fruto', kcReferencia: 0.80, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Verano. Fruto en crecimiento. Kc sostenido.' },
  { cultivo: 'citricos', mes: 2,  fase: 'desarrollo_fruto', kcReferencia: 0.82, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Pico de calor. Kc ligeramente superior por alta ET.' },
  { cultivo: 'citricos', mes: 3,  fase: 'maduracion',       kcReferencia: 0.78, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Otoño. Inicio maduración en naranjo tardío.' },
  { cultivo: 'citricos', mes: 4,  fase: 'cosecha',          kcReferencia: 0.72, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Cosecha limonero. Naranjo aún en maduración.' },
  { cultivo: 'citricos', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.65, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas', notas: 'Post-cosecha. Inicio invierno. Lluvias complementan riego.' },
  { cultivo: 'citricos', mes: 6,  fase: 'reposo',           kcReferencia: 0.62, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Invierno. Cítricos perennifolios; Kc mínimo pero no cero.' },
  { cultivo: 'citricos', mes: 7,  fase: 'reposo',           kcReferencia: 0.60, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Mes más frío. Kc mínimo anual en cítricos.' },
  { cultivo: 'citricos', mes: 8,  fase: 'brotacion',        kcReferencia: 0.63, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas', notas: 'Inicio brotación primaveral. Kc comienza a subir.' },
  { cultivo: 'citricos', mes: 9,  fase: 'floracion',        kcReferencia: 0.70, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Floración. Cítricos sensibles a estrés en esta fase.' },
  { cultivo: 'citricos', mes: 10, fase: 'cuaje',            kcReferencia: 0.75, umbralRojoDeficitPct: 38, umbralAmarilloDeficitPct: 28, fuente: 'FAO-56 tabla 12', notas: 'Cuaje. Mantener humedad para reducir caída fisiológica.' },
  { cultivo: 'citricos', mes: 11, fase: 'desarrollo_fruto', kcReferencia: 0.78, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Inicio engrose. Primavera avanzada.' },
  { cultivo: 'citricos', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 0.80, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Pleno verano. Demanda en alza.' },

  // ─── CIRUELA D'AGEN ───────────────────────────────────────────────────────
  { cultivo: 'ciruela_dagen', mes: 1,  fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Pico verano. Kc máximo. Engrose rápido.' },
  { cultivo: 'ciruela_dagen', mes: 2,  fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose final.' },
  { cultivo: 'ciruela_dagen', mes: 3,  fase: 'maduracion',       kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Maduración.' },
  { cultivo: 'ciruela_dagen', mes: 4,  fase: 'cosecha',          kcReferencia: 0.85, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Cosecha D\'Agen.' },
  { cultivo: 'ciruela_dagen', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Post-cosecha otoñal.' },
  { cultivo: 'ciruela_dagen', mes: 6,  fase: 'reposo',           kcReferencia: 0.55, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Inicio reposo invernal.' },
  { cultivo: 'ciruela_dagen', mes: 7,  fase: 'reposo',           kcReferencia: 0.50, umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno.' },
  { cultivo: 'ciruela_dagen', mes: 8,  fase: 'reposo',           kcReferencia: 0.55, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'INIA serie actas', notas: 'Fin reposo.' },
  { cultivo: 'ciruela_dagen', mes: 9,  fase: 'brotacion',        kcReferencia: 0.65, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Brotación.' },
  { cultivo: 'ciruela_dagen', mes: 10, fase: 'floracion',        kcReferencia: 0.75, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración plena.' },
  { cultivo: 'ciruela_dagen', mes: 11, fase: 'cuaje',            kcReferencia: 0.90, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y caída de frutos.' },
  { cultivo: 'ciruela_dagen', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.05, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Inicio engrose rápido.' },

  // ─── NOGALES ──────────────────────────────────────────────────────────────
  { cultivo: 'nogales', mes: 1,  fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Pleno verano. Kc máximo. Llenado de nuez.' },
  { cultivo: 'nogales', mes: 2,  fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Llenado final de almendra.' },
  { cultivo: 'nogales', mes: 3,  fase: 'maduracion',       kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Apertura de ruezno.' },
  { cultivo: 'nogales', mes: 4,  fase: 'cosecha',          kcReferencia: 0.80, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Cosecha principal.' },
  { cultivo: 'nogales', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.65, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Post-cosecha. Defoliación otoñal.' },
  { cultivo: 'nogales', mes: 6,  fase: 'reposo',           kcReferencia: 0.55, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'nogales', mes: 7,  fase: 'reposo',           kcReferencia: 0.50, umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55, fuente: 'FAO-56 tabla 12', notas: 'Mes más frío. Kc mínimo.' },
  { cultivo: 'nogales', mes: 8,  fase: 'reposo',           kcReferencia: 0.55, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'INIA serie actas', notas: 'Fin reposo.' },
  { cultivo: 'nogales', mes: 9,  fase: 'brotacion',        kcReferencia: 0.65, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Brotación.' },
  { cultivo: 'nogales', mes: 10, fase: 'floracion',        kcReferencia: 0.80, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración.' },
  { cultivo: 'nogales', mes: 11, fase: 'cuaje',            kcReferencia: 0.95, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje.' },
  { cultivo: 'nogales', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.05, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Inicio llenado de nuez.' },

  // ─── UVA DE MESA ──────────────────────────────────────────────────────────
  { cultivo: 'uva_mesa', mes: 1,  fase: 'maduracion',       kcReferencia: 0.85, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Pinta y maduración.' },
  { cultivo: 'uva_mesa', mes: 2,  fase: 'cosecha',          kcReferencia: 0.75, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Cosecha variedades tempranas.' },
  { cultivo: 'uva_mesa', mes: 3,  fase: 'cosecha',          kcReferencia: 0.60, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Cosecha media y tardía.' },
  { cultivo: 'uva_mesa', mes: 4,  fase: 'post_cosecha',     kcReferencia: 0.50, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Post-cosecha.' },
  { cultivo: 'uva_mesa', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.40, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas', notas: 'Defoliación otoñal.' },
  { cultivo: 'uva_mesa', mes: 6,  fase: 'reposo',           kcReferencia: 0.30, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'uva_mesa', mes: 7,  fase: 'reposo',           kcReferencia: 0.30, umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno. Podas de invierno.' },
  { cultivo: 'uva_mesa', mes: 8,  fase: 'reposo',           kcReferencia: 0.35, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas', notas: 'Fin reposo.' },
  { cultivo: 'uva_mesa', mes: 9,  fase: 'brotacion',        kcReferencia: 0.45, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Brotación.' },
  { cultivo: 'uva_mesa', mes: 10, fase: 'floracion',        kcReferencia: 0.60, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración.' },
  { cultivo: 'uva_mesa', mes: 11, fase: 'cuaje',            kcReferencia: 0.75, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y crecimiento de baya.' },
  { cultivo: 'uva_mesa', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 0.85, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Desarrollo baya. Kc máximo.' },

  // ─── UVA VINÍFERA ─────────────────────────────────────────────────────────
  { cultivo: 'uva_vinifera', mes: 1,  fase: 'maduracion',       kcReferencia: 0.70, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Pinta. Déficit moderado mejora concentración.' },
  { cultivo: 'uva_vinifera', mes: 2,  fase: 'maduracion',       kcReferencia: 0.65, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Estrés hídrico controlado.' },
  { cultivo: 'uva_vinifera', mes: 3,  fase: 'cosecha',          kcReferencia: 0.55, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'FAO-56 tabla 12', notas: 'Cosecha variedades tintas.' },
  { cultivo: 'uva_vinifera', mes: 4,  fase: 'cosecha',          kcReferencia: 0.45, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas', notas: 'Cosecha tardía.' },
  { cultivo: 'uva_vinifera', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.40, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas', notas: 'Post-cosecha.' },
  { cultivo: 'uva_vinifera', mes: 6,  fase: 'reposo',           kcReferencia: 0.30, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'uva_vinifera', mes: 7,  fase: 'reposo',           kcReferencia: 0.30, umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno. Poda invernal.' },
  { cultivo: 'uva_vinifera', mes: 8,  fase: 'reposo',           kcReferencia: 0.32, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas', notas: 'Fin reposo.' },
  { cultivo: 'uva_vinifera', mes: 9,  fase: 'brotacion',        kcReferencia: 0.40, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Brotación.' },
  { cultivo: 'uva_vinifera', mes: 10, fase: 'floracion',        kcReferencia: 0.50, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Floración y cuaje.' },
  { cultivo: 'uva_vinifera', mes: 11, fase: 'cuaje',            kcReferencia: 0.60, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y crecimiento herbáceo de baya.' },
  { cultivo: 'uva_vinifera', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 0.70, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Desarrollo de baya previo a pinta.' },

  // ─── MANZANO ──────────────────────────────────────────────────────────────
  { cultivo: 'manzano', mes: 1,  fase: 'desarrollo_fruto', kcReferencia: 1.20, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose fruto. Kc máximo.' },
  { cultivo: 'manzano', mes: 2,  fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose final.' },
  { cultivo: 'manzano', mes: 3,  fase: 'maduracion',       kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Cosecha variedades tempranas.' },
  { cultivo: 'manzano', mes: 4,  fase: 'cosecha',          kcReferencia: 0.90, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Cosecha principal.' },
  { cultivo: 'manzano', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.75, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Post-cosecha.' },
  { cultivo: 'manzano', mes: 6,  fase: 'reposo',           kcReferencia: 0.60, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'manzano', mes: 7,  fase: 'reposo',           kcReferencia: 0.55, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Mes más frío. Acumulación horas-frío.' },
  { cultivo: 'manzano', mes: 8,  fase: 'reposo',           kcReferencia: 0.60, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas', notas: 'Fin reposo.' },
  { cultivo: 'manzano', mes: 9,  fase: 'brotacion',        kcReferencia: 0.75, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Brotación y punta verde.' },
  { cultivo: 'manzano', mes: 10, fase: 'floracion',        kcReferencia: 0.90, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración plena.' },
  { cultivo: 'manzano', mes: 11, fase: 'cuaje',            kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y caída fisiológica.' },
  { cultivo: 'manzano', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose inicial.' },

  // ─── CEREZO ───────────────────────────────────────────────────────────────
  { cultivo: 'cerezo', mes: 1,  fase: 'post_cosecha',     kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Post-cosecha temprana. Formación yemas florales.' },
  { cultivo: 'cerezo', mes: 2,  fase: 'post_cosecha',     kcReferencia: 0.95, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Post-cosecha plena.' },
  { cultivo: 'cerezo', mes: 3,  fase: 'post_cosecha',     kcReferencia: 0.85, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Fin verano.' },
  { cultivo: 'cerezo', mes: 4,  fase: 'post_cosecha',     kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Otoño. Inicio defoliación.' },
  { cultivo: 'cerezo', mes: 5,  fase: 'reposo',           kcReferencia: 0.60, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas', notas: 'Defoliación otoñal.' },
  { cultivo: 'cerezo', mes: 6,  fase: 'reposo',           kcReferencia: 0.50, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'cerezo', mes: 7,  fase: 'reposo',           kcReferencia: 0.50, umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno.' },
  { cultivo: 'cerezo', mes: 8,  fase: 'reposo',           kcReferencia: 0.55, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas', notas: 'Fin reposo.' },
  { cultivo: 'cerezo', mes: 9,  fase: 'floracion',        kcReferencia: 0.75, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración temprana.' },
  { cultivo: 'cerezo', mes: 10, fase: 'cuaje',            kcReferencia: 0.95, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y crecimiento rápido.' },
  { cultivo: 'cerezo', mes: 11, fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose y maduración.' },
  { cultivo: 'cerezo', mes: 12, fase: 'cosecha',          kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cosecha principal.' },

  // ─── ARÁNDANO ─────────────────────────────────────────────────────────────
  { cultivo: 'arandano', mes: 1,  fase: 'cosecha',          kcReferencia: 1.00, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Cosecha principal. Raíz superficial.' },
  { cultivo: 'arandano', mes: 2,  fase: 'cosecha',          kcReferencia: 0.95, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Cosecha variedades tardías.' },
  { cultivo: 'arandano', mes: 3,  fase: 'post_cosecha',     kcReferencia: 0.80, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'INIA serie actas', notas: 'Fin cosecha. Recuperación planta.' },
  { cultivo: 'arandano', mes: 4,  fase: 'post_cosecha',     kcReferencia: 0.65, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Otoño. Diferenciación yemas florales.' },
  { cultivo: 'arandano', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.50, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Defoliación.' },
  { cultivo: 'arandano', mes: 6,  fase: 'reposo',           kcReferencia: 0.35, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'arandano', mes: 7,  fase: 'reposo',           kcReferencia: 0.30, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno.' },
  { cultivo: 'arandano', mes: 8,  fase: 'reposo',           kcReferencia: 0.35, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas', notas: 'Fin reposo.' },
  { cultivo: 'arandano', mes: 9,  fase: 'brotacion',        kcReferencia: 0.55, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'INIA serie actas', notas: 'Brotación y pre-floración.' },
  { cultivo: 'arandano', mes: 10, fase: 'floracion',        kcReferencia: 0.75, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Floración y cuaje. Muy sensible a déficit.' },
  { cultivo: 'arandano', mes: 11, fase: 'cuaje',            kcReferencia: 0.90, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y llenado baya.' },
  { cultivo: 'arandano', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.05, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Engrose baya. Kc máximo.' },

  // ─── DURAZNERO / NECTARINO ────────────────────────────────────────────────
  { cultivo: 'duraznero', mes: 1,  fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose y maduración variedades tempranas.' },
  { cultivo: 'duraznero', mes: 2,  fase: 'cosecha',          kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cosecha principal.' },
  { cultivo: 'duraznero', mes: 3,  fase: 'cosecha',          kcReferencia: 0.95, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'INIA serie actas', notas: 'Cosecha tardía.' },
  { cultivo: 'duraznero', mes: 4,  fase: 'post_cosecha',     kcReferencia: 0.80, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Post-cosecha.' },
  { cultivo: 'duraznero', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.65, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Otoño. Defoliación.' },
  { cultivo: 'duraznero', mes: 6,  fase: 'reposo',           kcReferencia: 0.55, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'duraznero', mes: 7,  fase: 'reposo',           kcReferencia: 0.50, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno.' },
  { cultivo: 'duraznero', mes: 8,  fase: 'reposo',           kcReferencia: 0.60, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas', notas: 'Fin reposo.' },
  { cultivo: 'duraznero', mes: 9,  fase: 'floracion',        kcReferencia: 0.80, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración temprana.' },
  { cultivo: 'duraznero', mes: 10, fase: 'cuaje',            kcReferencia: 0.95, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y endurecimiento carozo.' },
  { cultivo: 'duraznero', mes: 11, fase: 'desarrollo_fruto', kcReferencia: 1.05, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose II.' },
  { cultivo: 'duraznero', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose final. Kc máximo.' },

  // ─── ALMENDRO ─────────────────────────────────────────────────────────────
  { cultivo: 'almendro', mes: 1,  fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Llenado de almendra. Kc máximo.' },
  { cultivo: 'almendro', mes: 2,  fase: 'desarrollo_fruto', kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Llenado final.' },
  { cultivo: 'almendro', mes: 3,  fase: 'maduracion',       kcReferencia: 0.90, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Apertura de ruezno.' },
  { cultivo: 'almendro', mes: 4,  fase: 'cosecha',          kcReferencia: 0.75, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Cosecha.' },
  { cultivo: 'almendro', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.65, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Post-cosecha.' },
  { cultivo: 'almendro', mes: 6,  fase: 'reposo',           kcReferencia: 0.50, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal corto.' },
  { cultivo: 'almendro', mes: 7,  fase: 'reposo',           kcReferencia: 0.45, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno.' },
  { cultivo: 'almendro', mes: 8,  fase: 'floracion',        kcReferencia: 0.55, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Floración muy temprana.' },
  { cultivo: 'almendro', mes: 9,  fase: 'cuaje',            kcReferencia: 0.70, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y brotación.' },
  { cultivo: 'almendro', mes: 10, fase: 'brotacion',        kcReferencia: 0.85, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'INIA serie actas', notas: 'Desarrollo vegetativo.' },
  { cultivo: 'almendro', mes: 11, fase: 'desarrollo_fruto', kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Endurecimiento carozo.' },
  { cultivo: 'almendro', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Inicio llenado de almendra.' },

  // ─── OLIVO ────────────────────────────────────────────────────────────────
  { cultivo: 'olivo', mes: 1,  fase: 'desarrollo_fruto', kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'FAO-56 tabla 12', notas: 'Engrose fruto. Verano seco se tolera bien.' },
  { cultivo: 'olivo', mes: 2,  fase: 'desarrollo_fruto', kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'FAO-56 tabla 12', notas: 'Engrose pleno.' },
  { cultivo: 'olivo', mes: 3,  fase: 'maduracion',       kcReferencia: 0.70, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'FAO-56 tabla 12', notas: 'Inicio maduración. Envero.' },
  { cultivo: 'olivo', mes: 4,  fase: 'maduracion',       kcReferencia: 0.70, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Acumulación de aceite.' },
  { cultivo: 'olivo', mes: 5,  fase: 'cosecha',          kcReferencia: 0.70, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas', notas: 'Cosecha almazara.' },
  { cultivo: 'olivo', mes: 6,  fase: 'post_cosecha',     kcReferencia: 0.65, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Post-cosecha. Lluvias invernales.' },
  { cultivo: 'olivo', mes: 7,  fase: 'reposo',           kcReferencia: 0.65, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Invierno. Kc mínimo.' },
  { cultivo: 'olivo', mes: 8,  fase: 'reposo',           kcReferencia: 0.65, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Fin invierno. Diferenciación floral.' },
  { cultivo: 'olivo', mes: 9,  fase: 'brotacion',        kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas', notas: 'Brotación primaveral.' },
  { cultivo: 'olivo', mes: 10, fase: 'floracion',        kcReferencia: 0.70, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Floración. Déficit reduce cuaje.' },
  { cultivo: 'olivo', mes: 11, fase: 'cuaje',            kcReferencia: 0.70, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Cuaje. Sensible a déficit.' },
  { cultivo: 'olivo', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'FAO-56 tabla 12', notas: 'Inicio engrose. Verano comenzando.' },

  // ─── KIWI ─────────────────────────────────────────────────────────────────
  { cultivo: 'kiwi', mes: 1,  fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Engrose fruto. Muy sensible a déficit.' },
  { cultivo: 'kiwi', mes: 2,  fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Engrose pleno. ET máxima.' },
  { cultivo: 'kiwi', mes: 3,  fase: 'maduracion',       kcReferencia: 1.05, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Maduración.' },
  { cultivo: 'kiwi', mes: 4,  fase: 'cosecha',          kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cosecha.' },
  { cultivo: 'kiwi', mes: 5,  fase: 'post_cosecha',     kcReferencia: 0.80, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Post-cosecha.' },
  { cultivo: 'kiwi', mes: 6,  fase: 'reposo',           kcReferencia: 0.50, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'kiwi', mes: 7,  fase: 'reposo',           kcReferencia: 0.45, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno.' },
  { cultivo: 'kiwi', mes: 8,  fase: 'reposo',           kcReferencia: 0.50, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas', notas: 'Fin reposo.' },
  { cultivo: 'kiwi', mes: 9,  fase: 'brotacion',        kcReferencia: 0.65, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas', notas: 'Brotación.' },
  { cultivo: 'kiwi', mes: 10, fase: 'floracion',        kcReferencia: 0.85, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Floración. Polinización crítica.' },
  { cultivo: 'kiwi', mes: 11, fase: 'cuaje',            kcReferencia: 1.00, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y crecimiento rápido.' },
  { cultivo: 'kiwi', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Engrose I. Alta demanda sostenida.' },
];
