import type { EntradaFenologica } from './types';

// Hemisferio sur: enero = verano, julio = invierno/reposo
// Kc: FAO-56 tabla 12. Umbrales: estimación INIA adaptada a condiciones secano costero Chile.
// Umbral rojo = déficit crítico (regar hoy). Umbral amarillo = pre-alerta.
// Regla general: umbral rojo > umbral amarillo siempre.

export const CATALOGO_FENOLOGIA: EntradaFenologica[] = [
  // ─── PALTO HASS ───────────────────────────────────────────────────────────
  // Hemisferio sur: floracion oct-nov, cuaje dic, desarrollo ene-mar, cosecha abr-may
  {
    cultivo: 'palto_hass', mes: 1, fase: 'desarrollo_fruto',
    kcReferencia: 1.00,
    umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20,
    fuente: 'FAO-56 tabla 12',
    notas: 'Pleno verano. Demanda hídrica máxima. Fruto en engrose activo.',
  },
  {
    cultivo: 'palto_hass', mes: 2, fase: 'desarrollo_fruto',
    kcReferencia: 1.00,
    umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20,
    fuente: 'FAO-56 tabla 12',
    notas: 'Continúa engrose. Temperatura alta, ET elevada.',
  },
  {
    cultivo: 'palto_hass', mes: 3, fase: 'maduracion',
    kcReferencia: 0.95,
    umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25,
    fuente: 'FAO-56 tabla 12',
    notas: 'Inicio maduración. Kc baja levemente hacia otoño.',
  },
  {
    cultivo: 'palto_hass', mes: 4, fase: 'cosecha',
    kcReferencia: 0.85,
    umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30,
    fuente: 'FAO-56 tabla 12',
    notas: 'Cosecha principal variedades tempranas Hass. Reducir riego gradualmente.',
  },
  {
    cultivo: 'palto_hass', mes: 5, fase: 'post_cosecha',
    kcReferencia: 0.75,
    umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Post-cosecha. Recuperación foliar. Menor demanda.',
  },
  {
    cultivo: 'palto_hass', mes: 6, fase: 'reposo',
    kcReferencia: 0.60,
    umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Invierno. Crecimiento mínimo. Lluvias reducen necesidad de riego.',
  },
  {
    cultivo: 'palto_hass', mes: 7, fase: 'reposo',
    kcReferencia: 0.55,
    umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45,
    fuente: 'FAO-56 tabla 12',
    notas: 'Mes más frío. Kc mínimo anual. Riego de mantención solamente.',
  },
  {
    cultivo: 'palto_hass', mes: 8, fase: 'reposo',
    kcReferencia: 0.60,
    umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Fin invierno. Inicio diferenciación floral en yemas.',
  },
  {
    cultivo: 'palto_hass', mes: 9, fase: 'brotacion',
    kcReferencia: 0.70,
    umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Primavera temprana. Brotación. Kc en ascenso.',
  },
  {
    cultivo: 'palto_hass', mes: 10, fase: 'floracion',
    kcReferencia: 0.80,
    umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25,
    fuente: 'FAO-56 tabla 12',
    notas: 'Floración. Sensibilidad hídrica alta. Déficit afecta cuaje.',
  },
  {
    cultivo: 'palto_hass', mes: 11, fase: 'cuaje',
    kcReferencia: 0.90,
    umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20,
    fuente: 'FAO-56 tabla 12',
    notas: 'Cuaje y caída fisiológica. Mantener humedad uniforme.',
  },
  {
    cultivo: 'palto_hass', mes: 12, fase: 'desarrollo_fruto',
    kcReferencia: 0.95,
    umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20,
    fuente: 'FAO-56 tabla 12',
    notas: 'Inicio engrose rápido. Verano comenzando.',
  },

  // ─── CÍTRICOS (naranjo/limonero referencia, ajustable por especie) ─────────
  // Kc cítricos: 0.60 reposo a 0.85 verano (FAO-56 tabla 12)
  {
    cultivo: 'citricos', mes: 1, fase: 'desarrollo_fruto',
    kcReferencia: 0.80,
    umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25,
    fuente: 'FAO-56 tabla 12',
    notas: 'Verano. Fruto en crecimiento. Kc sostenido.',
  },
  {
    cultivo: 'citricos', mes: 2, fase: 'desarrollo_fruto',
    kcReferencia: 0.82,
    umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25,
    fuente: 'FAO-56 tabla 12',
    notas: 'Pico de calor. Kc ligeramente superior por alta ET.',
  },
  {
    cultivo: 'citricos', mes: 3, fase: 'maduracion',
    kcReferencia: 0.78,
    umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30,
    fuente: 'FAO-56 tabla 12',
    notas: 'Otoño. Inicio maduración en naranjo tardío.',
  },
  {
    cultivo: 'citricos', mes: 4, fase: 'cosecha',
    kcReferencia: 0.72,
    umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Cosecha limonero. Naranjo aún en maduración.',
  },
  {
    cultivo: 'citricos', mes: 5, fase: 'post_cosecha',
    kcReferencia: 0.65,
    umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Post-cosecha. Inicio invierno. Lluvias complementan riego.',
  },
  {
    cultivo: 'citricos', mes: 6, fase: 'reposo',
    kcReferencia: 0.62,
    umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45,
    fuente: 'FAO-56 tabla 12',
    notas: 'Invierno. Cítricos perennifolios; Kc mínimo pero no cero.',
  },
  {
    cultivo: 'citricos', mes: 7, fase: 'reposo',
    kcReferencia: 0.60,
    umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45,
    fuente: 'FAO-56 tabla 12',
    notas: 'Mes más frío. Kc mínimo anual en cítricos.',
  },
  {
    cultivo: 'citricos', mes: 8, fase: 'brotacion',
    kcReferencia: 0.63,
    umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Inicio brotación primaveral. Kc comienza a subir.',
  },
  {
    cultivo: 'citricos', mes: 9, fase: 'floracion',
    kcReferencia: 0.70,
    umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30,
    fuente: 'FAO-56 tabla 12',
    notas: 'Floración. Cítricos sensibles a estrés en esta fase.',
  },
  {
    cultivo: 'citricos', mes: 10, fase: 'cuaje',
    kcReferencia: 0.75,
    umbralRojoDeficitPct: 38, umbralAmarilloDeficitPct: 28,
    fuente: 'FAO-56 tabla 12',
    notas: 'Cuaje. Mantener humedad para reducir caída fisiológica.',
  },
  {
    cultivo: 'citricos', mes: 11, fase: 'desarrollo_fruto',
    kcReferencia: 0.78,
    umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25,
    fuente: 'FAO-56 tabla 12',
    notas: 'Inicio engrose. Primavera avanzada.',
  },
  {
    cultivo: 'citricos', mes: 12, fase: 'desarrollo_fruto',
    kcReferencia: 0.80,
    umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25,
    fuente: 'FAO-56 tabla 12',
    notas: 'Pleno verano. Demanda en alza.',
  },

  // ─── CIRUELA D'AGEN ───────────────────────────────────────────────────────
  // Kc ciruela: 0.50 reposo a 1.15 desarrollo fruto (FAO-56 tabla 12)
  // Hoja caduca: reposo invernal real (jun-jul)
  {
    cultivo: 'ciruela_dagen', mes: 1, fase: 'desarrollo_fruto',
    kcReferencia: 1.15,
    umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15,
    fuente: 'FAO-56 tabla 12',
    notas: 'Pico verano. Kc máximo. Engrose rápido. Déficit reduce tamaño fruto.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 2, fase: 'desarrollo_fruto',
    kcReferencia: 1.10,
    umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15,
    fuente: 'FAO-56 tabla 12',
    notas: 'Engrose final. Kc ligeramente menor al avanzar el verano.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 3, fase: 'maduracion',
    kcReferencia: 1.00,
    umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20,
    fuente: 'FAO-56 tabla 12',
    notas: 'Maduración. Calidad se logra con riego controlado (no exceso).',
  },
  {
    cultivo: 'ciruela_dagen', mes: 4, fase: 'cosecha',
    kcReferencia: 0.85,
    umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Cosecha D\'Agen. Reducir riego previo a cosecha para concentrar sólidos.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 5, fase: 'post_cosecha',
    kcReferencia: 0.70,
    umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Post-cosecha otoñal. Defoliación en curso. Demanda baja.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 6, fase: 'reposo',
    kcReferencia: 0.55,
    umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50,
    fuente: 'FAO-56 tabla 12',
    notas: 'Inicio reposo invernal. Árbol sin hojas. Lluvias sustentan.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 7, fase: 'reposo',
    kcReferencia: 0.50,
    umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55,
    fuente: 'FAO-56 tabla 12',
    notas: 'Reposo pleno. Kc mínimo. Sin riego bajo lluvia normal Chile centro.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 8, fase: 'reposo',
    kcReferencia: 0.55,
    umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Fin reposo. Inicio hinchazón yemas. Preparar sistema riego.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 9, fase: 'brotacion',
    kcReferencia: 0.65,
    umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Brotación. Retomar riego. Raíces activas, hojas emergiendo.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 10, fase: 'floracion',
    kcReferencia: 0.75,
    umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25,
    fuente: 'FAO-56 tabla 12',
    notas: 'Floración plena. Heladas tardías son el principal riesgo, no déficit.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 11, fase: 'cuaje',
    kcReferencia: 0.90,
    umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20,
    fuente: 'FAO-56 tabla 12',
    notas: 'Cuaje y caída de frutos. Déficit agrava caída.',
  },
  {
    cultivo: 'ciruela_dagen', mes: 12, fase: 'desarrollo_fruto',
    kcReferencia: 1.05,
    umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15,
    fuente: 'FAO-56 tabla 12',
    notas: 'Inicio engrose rápido. Kc en ascenso hacia máximo enero.',
  },

  // ─── NOGALES (Juglans regia) ──────────────────────────────────────────────
  // Kc nogal FAO-56 tabla 12: ini 0.50, mid 1.10, end 0.65. Caducifolio.
  // Hemisferio sur: reposo jun-ago, brotacion sep, floracion oct,
  // cuaje nov, desarrollo dic-ene, maduracion feb-mar, cosecha abr.
  {
    cultivo: 'nogales', mes: 1, fase: 'desarrollo_fruto',
    kcReferencia: 1.10,
    umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15,
    fuente: 'FAO-56 tabla 12',
    notas: 'Pleno verano. Kc máximo. Llenado de nuez. Alta sensibilidad a déficit.',
  },
  {
    cultivo: 'nogales', mes: 2, fase: 'desarrollo_fruto',
    kcReferencia: 1.10,
    umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15,
    fuente: 'FAO-56 tabla 12',
    notas: 'Llenado final de almendra. Déficit reduce calibre y calidad.',
  },
  {
    cultivo: 'nogales', mes: 3, fase: 'maduracion',
    kcReferencia: 1.00,
    umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20,
    fuente: 'FAO-56 tabla 12',
    notas: 'Maduración. Apertura de ruezno. Mantener riego para evitar estrés.',
  },
  {
    cultivo: 'nogales', mes: 4, fase: 'cosecha',
    kcReferencia: 0.80,
    umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Cosecha principal. Reducir riego para facilitar caída y secado.',
  },
  {
    cultivo: 'nogales', mes: 5, fase: 'post_cosecha',
    kcReferencia: 0.65,
    umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Post-cosecha. Defoliación otoñal. Riego de reposición.',
  },
  {
    cultivo: 'nogales', mes: 6, fase: 'reposo',
    kcReferencia: 0.55,
    umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50,
    fuente: 'FAO-56 tabla 12',
    notas: 'Reposo invernal. Árbol sin hojas. Lluvias sustentan el suelo.',
  },
  {
    cultivo: 'nogales', mes: 7, fase: 'reposo',
    kcReferencia: 0.50,
    umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55,
    fuente: 'FAO-56 tabla 12',
    notas: 'Mes más frío. Kc mínimo. Sin riego bajo lluvia normal Chile centro.',
  },
  {
    cultivo: 'nogales', mes: 8, fase: 'reposo',
    kcReferencia: 0.55,
    umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Fin reposo. Hinchazón de yemas. Preparar sistema de riego.',
  },
  {
    cultivo: 'nogales', mes: 9, fase: 'brotacion',
    kcReferencia: 0.65,
    umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35,
    fuente: 'INIA serie actas N°XX (estimación)',
    notas: 'Brotación. Retomar riego. Raíces reactivas, hojas emergiendo.',
  },
  {
    cultivo: 'nogales', mes: 10, fase: 'floracion',
    kcReferencia: 0.80,
    umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25,
    fuente: 'FAO-56 tabla 12',
    notas: 'Floración. Sensibilidad a heladas tardías más que a déficit.',
  },
  {
    cultivo: 'nogales', mes: 11, fase: 'cuaje',
    kcReferencia: 0.95,
    umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20,
    fuente: 'FAO-56 tabla 12',
    notas: 'Cuaje. Kc en ascenso rápido. Mantener humedad uniforme.',
  },
  {
    cultivo: 'nogales', mes: 12, fase: 'desarrollo_fruto',
    kcReferencia: 1.05,
    umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15,
    fuente: 'FAO-56 tabla 12',
    notas: 'Inicio llenado de nuez. Kc cerca del máximo anual.',
  },

  // ─── UVA DE MESA ──────────────────────────────────────────────────────────
  // Kc FAO-56: ini 0.30, mid 0.85, end 0.45. Caducifolio. Brota sep, cosecha ene-mar.
  { cultivo: 'uva_mesa', mes: 1, fase: 'maduracion', kcReferencia: 0.85, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Pinta y maduración. Riego controlado para concentrar azúcares.' },
  { cultivo: 'uva_mesa', mes: 2, fase: 'cosecha', kcReferencia: 0.75, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Cosecha variedades tempranas. Reducir riego previo a cosecha.' },
  { cultivo: 'uva_mesa', mes: 3, fase: 'cosecha', kcReferencia: 0.60, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Cosecha media y tardía. Riego mínimo post-cosecha.' },
  { cultivo: 'uva_mesa', mes: 4, fase: 'post_cosecha', kcReferencia: 0.50, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Post-cosecha. Recuperación foliar antes de defoliación.' },
  { cultivo: 'uva_mesa', mes: 5, fase: 'post_cosecha', kcReferencia: 0.40, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Defoliación otoñal. Demanda baja.' },
  { cultivo: 'uva_mesa', mes: 6, fase: 'reposo', kcReferencia: 0.30, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal. Sin hojas. Lluvias sustentan suelo.' },
  { cultivo: 'uva_mesa', mes: 7, fase: 'reposo', kcReferencia: 0.30, umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno. Podas de invierno.' },
  { cultivo: 'uva_mesa', mes: 8, fase: 'reposo', kcReferencia: 0.35, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Fin reposo. Preparar sistema de riego.' },
  { cultivo: 'uva_mesa', mes: 9, fase: 'brotacion', kcReferencia: 0.45, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Brotación. Retomar riego suave.' },
  { cultivo: 'uva_mesa', mes: 10, fase: 'floracion', kcReferencia: 0.60, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración. Sensibilidad a déficit por cuaje.' },
  { cultivo: 'uva_mesa', mes: 11, fase: 'cuaje', kcReferencia: 0.75, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y crecimiento de baya. Kc en ascenso.' },
  { cultivo: 'uva_mesa', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 0.85, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Desarrollo baya. Kc máximo. Alta sensibilidad hídrica.' },

  // ─── UVA VINÍFERA ─────────────────────────────────────────────────────────
  // Kc FAO-56: ini 0.30, mid 0.70, end 0.45. Déficit controlado para calidad.
  { cultivo: 'uva_vinifera', mes: 1, fase: 'maduracion', kcReferencia: 0.70, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Pinta. Déficit moderado mejora concentración y color.' },
  { cultivo: 'uva_vinifera', mes: 2, fase: 'maduracion', kcReferencia: 0.65, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Estrés hídrico controlado es parte del manejo enológico.' },
  { cultivo: 'uva_vinifera', mes: 3, fase: 'cosecha', kcReferencia: 0.55, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'FAO-56 tabla 12', notas: 'Cosecha variedades tintas. Riego mínimo.' },
  { cultivo: 'uva_vinifera', mes: 4, fase: 'cosecha', kcReferencia: 0.45, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Cosecha tardía (Cabernet, Carmenere). Post-cosecha inicia.' },
  { cultivo: 'uva_vinifera', mes: 5, fase: 'post_cosecha', kcReferencia: 0.40, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Post-cosecha. Acumulación reservas antes de defoliación.' },
  { cultivo: 'uva_vinifera', mes: 6, fase: 'reposo', kcReferencia: 0.30, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal. Sin riego bajo lluvia normal.' },
  { cultivo: 'uva_vinifera', mes: 7, fase: 'reposo', kcReferencia: 0.30, umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno. Poda invernal.' },
  { cultivo: 'uva_vinifera', mes: 8, fase: 'reposo', kcReferencia: 0.32, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Fin reposo. Lloronas en yemas indican reactivación.' },
  { cultivo: 'uva_vinifera', mes: 9, fase: 'brotacion', kcReferencia: 0.40, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Brotación. Heladas tardías son mayor riesgo que déficit.' },
  { cultivo: 'uva_vinifera', mes: 10, fase: 'floracion', kcReferencia: 0.50, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Floración y cuaje. Riego suave.' },
  { cultivo: 'uva_vinifera', mes: 11, fase: 'cuaje', kcReferencia: 0.60, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y crecimiento herbáceo de baya.' },
  { cultivo: 'uva_vinifera', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 0.70, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Desarrollo de baya previo a pinta. Kc máximo.' },

  // ─── MANZANO ──────────────────────────────────────────────────────────────
  // Kc FAO-56: ini 0.60, mid 1.20, end 0.95 (con cubierta). Caducifolio.
  { cultivo: 'manzano', mes: 1, fase: 'desarrollo_fruto', kcReferencia: 1.20, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose fruto. Kc máximo. Déficit reduce calibre.' },
  { cultivo: 'manzano', mes: 2, fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose final. Demanda hídrica alta.' },
  { cultivo: 'manzano', mes: 3, fase: 'maduracion', kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Cosecha variedades tempranas (Gala).' },
  { cultivo: 'manzano', mes: 4, fase: 'cosecha', kcReferencia: 0.90, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Cosecha principal (Fuji, Pink Lady). Riego controlado.' },
  { cultivo: 'manzano', mes: 5, fase: 'post_cosecha', kcReferencia: 0.75, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Post-cosecha. Acumulación de reservas.' },
  { cultivo: 'manzano', mes: 6, fase: 'reposo', kcReferencia: 0.60, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal. Sin hojas.' },
  { cultivo: 'manzano', mes: 7, fase: 'reposo', kcReferencia: 0.55, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Mes más frío. Acumulación de horas-frío.' },
  { cultivo: 'manzano', mes: 8, fase: 'reposo', kcReferencia: 0.60, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Fin reposo. Hinchazón de yemas.' },
  { cultivo: 'manzano', mes: 9, fase: 'brotacion', kcReferencia: 0.75, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Brotación y punta verde.' },
  { cultivo: 'manzano', mes: 10, fase: 'floracion', kcReferencia: 0.90, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración plena. Cuidar heladas tardías.' },
  { cultivo: 'manzano', mes: 11, fase: 'cuaje', kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y caída fisiológica. Raleo.' },
  { cultivo: 'manzano', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose inicial. Kc cerca del máximo.' },

  // ─── CEREZO ───────────────────────────────────────────────────────────────
  // Kc FAO-56: ini 0.50, mid 1.20, end 0.85. Cosecha muy temprana (nov-dic).
  { cultivo: 'cerezo', mes: 1, fase: 'post_cosecha', kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Post-cosecha temprana. Formación yemas florales próxima temporada.' },
  { cultivo: 'cerezo', mes: 2, fase: 'post_cosecha', kcReferencia: 0.95, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Post-cosecha plena. Mantener reservas.' },
  { cultivo: 'cerezo', mes: 3, fase: 'post_cosecha', kcReferencia: 0.85, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Fin verano. Árbol acumula carbohidratos.' },
  { cultivo: 'cerezo', mes: 4, fase: 'post_cosecha', kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Otoño. Inicio defoliación.' },
  { cultivo: 'cerezo', mes: 5, fase: 'reposo', kcReferencia: 0.60, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Defoliación otoñal. Demanda baja.' },
  { cultivo: 'cerezo', mes: 6, fase: 'reposo', kcReferencia: 0.50, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal. Acumulación horas-frío crítica.' },
  { cultivo: 'cerezo', mes: 7, fase: 'reposo', kcReferencia: 0.50, umbralRojoDeficitPct: 65, umbralAmarilloDeficitPct: 55, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno. Sin riego bajo lluvia normal.' },
  { cultivo: 'cerezo', mes: 8, fase: 'reposo', kcReferencia: 0.55, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Fin reposo. Hinchazón yemas.' },
  { cultivo: 'cerezo', mes: 9, fase: 'floracion', kcReferencia: 0.75, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración temprana. Riesgo alto de heladas.' },
  { cultivo: 'cerezo', mes: 10, fase: 'cuaje', kcReferencia: 0.95, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y crecimiento rápido. Alta sensibilidad hídrica.' },
  { cultivo: 'cerezo', mes: 11, fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose y maduración. Evitar partidura por exceso de riego previo.' },
  { cultivo: 'cerezo', mes: 12, fase: 'cosecha', kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cosecha principal. Riego muy controlado antes de cosecha.' },

  // ─── ARÁNDANO ─────────────────────────────────────────────────────────────
  // Kc FAO-56: ini 0.30, mid 1.05, end 0.50. Raíz superficial, sensible.
  { cultivo: 'arandano', mes: 1, fase: 'cosecha', kcReferencia: 1.00, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Cosecha principal. Raíz superficial: riego frecuente, sin déficit.' },
  { cultivo: 'arandano', mes: 2, fase: 'cosecha', kcReferencia: 0.95, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Cosecha variedades tardías. Mantener humedad uniforme.' },
  { cultivo: 'arandano', mes: 3, fase: 'post_cosecha', kcReferencia: 0.80, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Fin cosecha. Recuperación planta.' },
  { cultivo: 'arandano', mes: 4, fase: 'post_cosecha', kcReferencia: 0.65, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Otoño. Diferenciación yemas florales.' },
  { cultivo: 'arandano', mes: 5, fase: 'post_cosecha', kcReferencia: 0.50, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Defoliación. Demanda menor.' },
  { cultivo: 'arandano', mes: 6, fase: 'reposo', kcReferencia: 0.35, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal. Horas-frío críticas.' },
  { cultivo: 'arandano', mes: 7, fase: 'reposo', kcReferencia: 0.30, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Mes más frío. Reposo pleno.' },
  { cultivo: 'arandano', mes: 8, fase: 'reposo', kcReferencia: 0.35, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Fin reposo. Preparación poda.' },
  { cultivo: 'arandano', mes: 9, fase: 'brotacion', kcReferencia: 0.55, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Brotación y pre-floración.' },
  { cultivo: 'arandano', mes: 10, fase: 'floracion', kcReferencia: 0.75, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Floración y cuaje. Muy sensible a déficit.' },
  { cultivo: 'arandano', mes: 11, fase: 'cuaje', kcReferencia: 0.90, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y llenado baya. Calibre depende del riego.' },
  { cultivo: 'arandano', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.05, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Engrose baya. Kc máximo. Inicio cosecha variedades tempranas.' },

  // ─── DURAZNERO / NECTARINO ────────────────────────────────────────────────
  // Kc FAO-56: ini 0.55, mid 1.15, end 0.85. Caducifolio.
  { cultivo: 'duraznero', mes: 1, fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose y maduración variedades tempranas.' },
  { cultivo: 'duraznero', mes: 2, fase: 'cosecha', kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cosecha principal. Riego controlado para calidad.' },
  { cultivo: 'duraznero', mes: 3, fase: 'cosecha', kcReferencia: 0.95, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Cosecha tardía (conservero).' },
  { cultivo: 'duraznero', mes: 4, fase: 'post_cosecha', kcReferencia: 0.80, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Post-cosecha. Recuperación y diferenciación floral.' },
  { cultivo: 'duraznero', mes: 5, fase: 'post_cosecha', kcReferencia: 0.65, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Otoño. Defoliación.' },
  { cultivo: 'duraznero', mes: 6, fase: 'reposo', kcReferencia: 0.55, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'duraznero', mes: 7, fase: 'reposo', kcReferencia: 0.50, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno. Mes más frío.' },
  { cultivo: 'duraznero', mes: 8, fase: 'reposo', kcReferencia: 0.60, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Fin reposo. Hinchazón yemas.' },
  { cultivo: 'duraznero', mes: 9, fase: 'floracion', kcReferencia: 0.80, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Floración temprana. Riesgo de heladas.' },
  { cultivo: 'duraznero', mes: 10, fase: 'cuaje', kcReferencia: 0.95, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y endurecimiento carozo. Raleo.' },
  { cultivo: 'duraznero', mes: 11, fase: 'desarrollo_fruto', kcReferencia: 1.05, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose II. Sensibilidad hídrica alta.' },
  { cultivo: 'duraznero', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.15, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Engrose final. Kc máximo.' },

  // ─── ALMENDRO ─────────────────────────────────────────────────────────────
  // Kc FAO-56: ini 0.40, mid 1.15, end 0.65. Caducifolio. Floración muy temprana.
  { cultivo: 'almendro', mes: 1, fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Llenado de almendra. Kc máximo.' },
  { cultivo: 'almendro', mes: 2, fase: 'desarrollo_fruto', kcReferencia: 1.05, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Llenado final. Endurecimiento cáscara.' },
  { cultivo: 'almendro', mes: 3, fase: 'maduracion', kcReferencia: 0.90, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Apertura de ruezno.' },
  { cultivo: 'almendro', mes: 4, fase: 'cosecha', kcReferencia: 0.75, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Cosecha. Reducir riego para facilitar caída.' },
  { cultivo: 'almendro', mes: 5, fase: 'post_cosecha', kcReferencia: 0.65, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Post-cosecha. Defoliación otoñal.' },
  { cultivo: 'almendro', mes: 6, fase: 'reposo', kcReferencia: 0.50, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal corto.' },
  { cultivo: 'almendro', mes: 7, fase: 'reposo', kcReferencia: 0.45, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno. Horas-frío.' },
  { cultivo: 'almendro', mes: 8, fase: 'floracion', kcReferencia: 0.55, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Floración muy temprana (fin invierno). Riesgo alto de heladas.' },
  { cultivo: 'almendro', mes: 9, fase: 'cuaje', kcReferencia: 0.70, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y brotación. Retomar riego.' },
  { cultivo: 'almendro', mes: 10, fase: 'brotacion', kcReferencia: 0.85, umbralRojoDeficitPct: 35, umbralAmarilloDeficitPct: 25, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Desarrollo vegetativo. Crecimiento fruto.' },
  { cultivo: 'almendro', mes: 11, fase: 'desarrollo_fruto', kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Endurecimiento carozo. Sensible a déficit.' },
  { cultivo: 'almendro', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Inicio llenado de almendra. Kc cerca del máximo.' },

  // ─── OLIVO ────────────────────────────────────────────────────────────────
  // Kc FAO-56: ini 0.65, mid 0.70, end 0.70. Perennifolio, tolerante a sequía.
  { cultivo: 'olivo', mes: 1, fase: 'desarrollo_fruto', kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'FAO-56 tabla 12', notas: 'Engrose fruto. Verano seco se tolera bien.' },
  { cultivo: 'olivo', mes: 2, fase: 'desarrollo_fruto', kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'FAO-56 tabla 12', notas: 'Engrose pleno. Déficit moderado aceptable.' },
  { cultivo: 'olivo', mes: 3, fase: 'maduracion', kcReferencia: 0.70, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'FAO-56 tabla 12', notas: 'Inicio maduración. Envero.' },
  { cultivo: 'olivo', mes: 4, fase: 'maduracion', kcReferencia: 0.70, umbralRojoDeficitPct: 50, umbralAmarilloDeficitPct: 40, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Acumulación de aceite.' },
  { cultivo: 'olivo', mes: 5, fase: 'cosecha', kcReferencia: 0.70, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Cosecha almazara. Mesa se cosecha antes.' },
  { cultivo: 'olivo', mes: 6, fase: 'post_cosecha', kcReferencia: 0.65, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo relativo (perennifolio). Lluvias invernales sustentan.' },
  { cultivo: 'olivo', mes: 7, fase: 'reposo', kcReferencia: 0.65, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Invierno. Kc mínimo.' },
  { cultivo: 'olivo', mes: 8, fase: 'reposo', kcReferencia: 0.65, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Fin invierno. Inicio diferenciación floral.' },
  { cultivo: 'olivo', mes: 9, fase: 'brotacion', kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Brotación primaveral.' },
  { cultivo: 'olivo', mes: 10, fase: 'floracion', kcReferencia: 0.70, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Floración. Déficit en esta fase reduce cuaje.' },
  { cultivo: 'olivo', mes: 11, fase: 'cuaje', kcReferencia: 0.70, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'FAO-56 tabla 12', notas: 'Cuaje. Sensible a déficit.' },
  { cultivo: 'olivo', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 0.70, umbralRojoDeficitPct: 45, umbralAmarilloDeficitPct: 35, fuente: 'FAO-56 tabla 12', notas: 'Inicio engrose. Verano comenzando.' },

  // ─── KIWI ─────────────────────────────────────────────────────────────────
  // Kc FAO-56: ini 0.40, mid 1.05, end 1.05. Alta demanda hídrica sostenida.
  { cultivo: 'kiwi', mes: 1, fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Engrose fruto. Muy sensible a déficit, raíz superficial.' },
  { cultivo: 'kiwi', mes: 2, fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Engrose pleno. ET máxima.' },
  { cultivo: 'kiwi', mes: 3, fase: 'maduracion', kcReferencia: 1.05, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Maduración. Acumulación de sólidos solubles.' },
  { cultivo: 'kiwi', mes: 4, fase: 'cosecha', kcReferencia: 1.00, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Cosecha. Mantener riego hasta final.' },
  { cultivo: 'kiwi', mes: 5, fase: 'post_cosecha', kcReferencia: 0.80, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Post-cosecha. Defoliación próxima.' },
  { cultivo: 'kiwi', mes: 6, fase: 'reposo', kcReferencia: 0.50, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'FAO-56 tabla 12', notas: 'Reposo invernal.' },
  { cultivo: 'kiwi', mes: 7, fase: 'reposo', kcReferencia: 0.45, umbralRojoDeficitPct: 60, umbralAmarilloDeficitPct: 50, fuente: 'FAO-56 tabla 12', notas: 'Reposo pleno.' },
  { cultivo: 'kiwi', mes: 8, fase: 'reposo', kcReferencia: 0.50, umbralRojoDeficitPct: 55, umbralAmarilloDeficitPct: 45, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Fin reposo. Hinchazón yemas.' },
  { cultivo: 'kiwi', mes: 9, fase: 'brotacion', kcReferencia: 0.65, umbralRojoDeficitPct: 40, umbralAmarilloDeficitPct: 30, fuente: 'INIA serie actas N°XX (estimación)', notas: 'Brotación. Retomar riego.' },
  { cultivo: 'kiwi', mes: 10, fase: 'floracion', kcReferencia: 0.85, umbralRojoDeficitPct: 30, umbralAmarilloDeficitPct: 20, fuente: 'FAO-56 tabla 12', notas: 'Floración. Polinización crítica.' },
  { cultivo: 'kiwi', mes: 11, fase: 'cuaje', kcReferencia: 1.00, umbralRojoDeficitPct: 25, umbralAmarilloDeficitPct: 15, fuente: 'FAO-56 tabla 12', notas: 'Cuaje y crecimiento rápido.' },
  { cultivo: 'kiwi', mes: 12, fase: 'desarrollo_fruto', kcReferencia: 1.10, umbralRojoDeficitPct: 20, umbralAmarilloDeficitPct: 10, fuente: 'FAO-56 tabla 12', notas: 'Engrose I. Alta demanda sostenida.' },
];
